name: Update solo-apis
on:
  #release:
  #  types: [created]
  workflow_dispatch: # TEMP
    inputs:
      release-tag-name:
        description: 'release tag name'
        required: false
        default: ''
      release-branch-name:
        description: 'release branch name'
        required: false
        default: ''
jobs:
  publish-apis:
    env:
      # The tag for the release commit (ie v1.8.0)
      RELEASE_TAG_NAME: ${{github.event.inputs.release-tag-name}} # ${{ github.event.release.tag_name }}
      # The LTS branch that was released (ie v1.8.x)
      RELEASE_BRANCH: ${{github.event.inputs.release-branch-name}} # ${{ github.event.release.target_commitish }}
      # The tag to apply after merging the published apis (ie gloo-v1.8.0)
      SOLO_APIS_RELEASE_TAG_NAME: 'gloo-${{ env.RELEASE_TAG_NAME }}'
      # The LTS branch in solo-apis that will hold the published apis (ie gloo-v1.8.x)
      SOLO_APIS_RELEASE_BRANCH: 'gloo-${{ env.RELEASE_BRANCH }}'
      # The branch that this GHA will commit to.
      # The structure of this branch name allows the solo-apis repo to generate pull requests
      # to LTS branches in solo-apis that track gloo and generate corresponding tags
      # For example, releasing v1.8.0 will create a pull request:
      #   gloo-v1.8.x <-- sync-apis/gloo-v1.8.x/gloo-v1.8.0
      SOLO_APIS_SOURCE_BRANCH: 'sync-apis/${{ env.SOLO_APIS_RELEASE_BRANCH }}/${{ env.SOLO_APIS_RELEASE_TAG_NAME }}'
      # GitHub user details
      GIT_USER_NAME: soloio-bot
      GIT_USER_EMAIL: soloio-bot@github.com
    name: Publish Gloo APIs
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Free disk space
        run: |
          echo "Before clearing disk space:"
          df -h

          # https://github.com/actions/virtual-environments/issues/709
          sudo apt-get clean

          # Clean up pre-installed tools
          # https://github.com/actions/virtual-environments/issues/1918
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY

          echo "After clearing disk space:"
          df -h
      - name: Install SSH Deploy key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SOLO_API_DEPLOY_KEY }}
      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: gloo
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: solo-io/solo-apis
          path: solo-apis
          # Ensure that we checkout the solo-apis LTS branch initially (ie gloo-v1.8.x)
          ref: ${{ env.SOLO_APIS_RELEASE_BRANCH }}
      - name: Update solo-apis
        run: |
          cd solo-apis
          make mod-download update-deps; ./hack/sync-gloo-apis.sh; make generate
          git config --local user.name ${{ env.GIT_USER_NAME }}
          git config --local user.email ${{ env.GIT_USER_EMAIL }}
          git add .
          git checkout -B ${{ env.SOLO_APIS_SOURCE_BRANCH }}
          git commit -m "Sync Gloo APIs" --allow-empty
          git remote add solo-apis git@github.com:solo-io/solo-apis.git
          git push solo-apis ${{ env.SOLO_APIS_SOURCE_BRANCH }}
